plugins {
    alias libs.plugins.android.application
    alias libs.plugins.google.devtools.ksp
    alias libs.plugins.jetbrains.kotlin.plugin.compose
}

android {
    compileSdk 37

    defaultConfig {
        applicationId "ca.avendor.pogostrings"
        minSdk 33
        targetSdk 37
        versionCode 8
        versionName "1.5"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        compose true
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'ca.avendor.pogostrings'
}

dependencies {
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.graphics
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.material3
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.compose.material
    implementation libs.androidx.datastore.core
    implementation libs.androidx.room.common
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest


    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.gson
    implementation libs.material
    implementation libs.androidx.constraintlayout
    androidTestImplementation libs.androidx.espresso.core
    implementation libs.androidx.compose.material.icons.extended
    implementation platform(libs.kotlin.bom)

    // Coroutines
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    // Coroutine Lifecycle Scopes
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.runtime.ktx


    implementation libs.androidx.room.ktx
    ksp libs.androidx.room.compiler
}